name: Build

on: [ push ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            $CONDA/bin
            /tmp
          key: ${{ runner.os }}-$GITHUB_RUN_ID
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          # install dependencies from bioconda
          conda install -c conda-forge -c bioconda drop
          # reinstall DROP from source
          pip install .
      - name: Lint with flake8
        run: |
          conda install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --builtins="snakemake" --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  setup-pytest:
    needs: build-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            $CONDA/bin
            /tmp
          key: ${{ runner.os }}-$GITHUB_RUN_ID
      - name: Set conda path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
          echo $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda install pytest
          pip install -r tests/requirements.txt
      - name: Setup fixtures
          run: pytest --durations 0 tests/config

  test-pipeline:
    needs: setup-pytest
    strategy:
      matrix:
        pipeline: [ AE, AS, MAE, pipeline ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            $CONDA/bin
            /tmp
          key: ${{ runner.os }}-$GITHUB_RUN_ID
      - name: Set conda path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
          echo $GITHUB_PATH
      - name: ${{ matrix.pipeline }}
        run: pytest --durations 0 tests/pipeline/test_${{ matrix.pipeline }}.py
